name: ddd_generator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/simplifit-michael/ddd_generator.git
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.5
  ddd_annotations:
    git: https://github.com/simplifit-michael/ddd_annotations.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0